### ISSUE TITLE
cannot access db from my machine

### ISSUE THREAD

**Issue by catarinawor** [pbs-assess/juvenile-salmon-index#1]
I tried running Cam's script but I am getting an error in the sqlQuery() [call](https://github.com/pbs-assess/juvenile-salmon-index/blob/94e24512a918ac2aa9e45ffa94222061fbd40155/R/highSeasIPESClean.R#L26)  .

The error I get is: Could not find file 'Z:\\Highseas Access database\\HSSALMON_be.accdb'

Any idea of what is going on?

**Comment by CamFreshwater** [comment]
Ok I didn't realize that the directory where the backend for the older high seas database was stored was locked. I've made a copy of the backend (which we won't ever ever touch!) to the directory that you _do_ have access to so the script _should_ work now. 

When you have a chance, check, then close this if it's ok. Otherwise I'll go back to the drawing board!

**Comment by catarinawor** [comment]
all good! thanks for sorting it out, Cam!
